/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavoirFaireRouteImport } from './routes/savoir-faire'
import { Route as RgpdRouteImport } from './routes/rgpd'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MaisonsRouteImport } from './routes/maisons'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfigurateurRouteImport } from './routes/configurateur'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaisonsSlugRouteImport } from './routes/maisons.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavoirFaireRoute = SavoirFaireRouteImport.update({
  id: '/savoir-faire',
  path: '/savoir-faire',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpdRoute = RgpdRouteImport.update({
  id: '/rgpd',
  path: '/rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsRoute = MaisonsRouteImport.update({
  id: '/maisons',
  path: '/maisons',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurateurRoute = ConfigurateurRouteImport.update({
  id: '/configurateur',
  path: '/configurateur',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsSlugRoute = MaisonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MaisonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/cgv': typeof CgvRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/rgpd': typeof RgpdRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/cgv': typeof CgvRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/rgpd': typeof RgpdRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/cgv': typeof CgvRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/rgpd': typeof RgpdRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/cgv'
    | '/configurateur'
    | '/contact'
    | '/cookies'
    | '/maisons'
    | '/mentions-legales'
    | '/realisations'
    | '/rgpd'
    | '/savoir-faire'
    | '/sitemap.xml'
    | '/maisons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/cgv'
    | '/configurateur'
    | '/contact'
    | '/cookies'
    | '/maisons'
    | '/mentions-legales'
    | '/realisations'
    | '/rgpd'
    | '/savoir-faire'
    | '/sitemap.xml'
    | '/maisons/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/cgv'
    | '/configurateur'
    | '/contact'
    | '/cookies'
    | '/maisons'
    | '/mentions-legales'
    | '/realisations'
    | '/rgpd'
    | '/savoir-faire'
    | '/sitemap.xml'
    | '/maisons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  CgvRoute: typeof CgvRoute
  ConfigurateurRoute: typeof ConfigurateurRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  MaisonsRoute: typeof MaisonsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RealisationsRoute: typeof RealisationsRoute
  RgpdRoute: typeof RgpdRoute
  SavoirFaireRoute: typeof SavoirFaireRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savoir-faire': {
      id: '/savoir-faire'
      path: '/savoir-faire'
      fullPath: '/savoir-faire'
      preLoaderRoute: typeof SavoirFaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgpd': {
      id: '/rgpd'
      path: '/rgpd'
      fullPath: '/rgpd'
      preLoaderRoute: typeof RgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons': {
      id: '/maisons'
      path: '/maisons'
      fullPath: '/maisons'
      preLoaderRoute: typeof MaisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurateur': {
      id: '/configurateur'
      path: '/configurateur'
      fullPath: '/configurateur'
      preLoaderRoute: typeof ConfigurateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons/$slug': {
      id: '/maisons/$slug'
      path: '/$slug'
      fullPath: '/maisons/$slug'
      preLoaderRoute: typeof MaisonsSlugRouteImport
      parentRoute: typeof MaisonsRoute
    }
  }
}

interface MaisonsRouteChildren {
  MaisonsSlugRoute: typeof MaisonsSlugRoute
}

const MaisonsRouteChildren: MaisonsRouteChildren = {
  MaisonsSlugRoute: MaisonsSlugRoute,
}

const MaisonsRouteWithChildren =
  MaisonsRoute._addFileChildren(MaisonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  CgvRoute: CgvRoute,
  ConfigurateurRoute: ConfigurateurRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  MaisonsRoute: MaisonsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RealisationsRoute: RealisationsRoute,
  RgpdRoute: RgpdRoute,
  SavoirFaireRoute: SavoirFaireRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
