/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavoirFaireRouteImport } from './routes/savoir-faire'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as MaisonsRouteImport } from './routes/maisons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfigurateurRouteImport } from './routes/configurateur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaisonsSlugRouteImport } from './routes/maisons.$slug'

const SavoirFaireRoute = SavoirFaireRouteImport.update({
  id: '/savoir-faire',
  path: '/savoir-faire',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsRoute = MaisonsRouteImport.update({
  id: '/maisons',
  path: '/maisons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurateurRoute = ConfigurateurRouteImport.update({
  id: '/configurateur',
  path: '/configurateur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsSlugRoute = MaisonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MaisonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/maisons': typeof MaisonsRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurateur'
    | '/contact'
    | '/maisons'
    | '/realisations'
    | '/savoir-faire'
    | '/maisons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurateur'
    | '/contact'
    | '/maisons'
    | '/realisations'
    | '/savoir-faire'
    | '/maisons/$slug'
  id:
    | '__root__'
    | '/'
    | '/configurateur'
    | '/contact'
    | '/maisons'
    | '/realisations'
    | '/savoir-faire'
    | '/maisons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurateurRoute: typeof ConfigurateurRoute
  ContactRoute: typeof ContactRoute
  MaisonsRoute: typeof MaisonsRouteWithChildren
  RealisationsRoute: typeof RealisationsRoute
  SavoirFaireRoute: typeof SavoirFaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/savoir-faire': {
      id: '/savoir-faire'
      path: '/savoir-faire'
      fullPath: '/savoir-faire'
      preLoaderRoute: typeof SavoirFaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons': {
      id: '/maisons'
      path: '/maisons'
      fullPath: '/maisons'
      preLoaderRoute: typeof MaisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurateur': {
      id: '/configurateur'
      path: '/configurateur'
      fullPath: '/configurateur'
      preLoaderRoute: typeof ConfigurateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons/$slug': {
      id: '/maisons/$slug'
      path: '/$slug'
      fullPath: '/maisons/$slug'
      preLoaderRoute: typeof MaisonsSlugRouteImport
      parentRoute: typeof MaisonsRoute
    }
  }
}

interface MaisonsRouteChildren {
  MaisonsSlugRoute: typeof MaisonsSlugRoute
}

const MaisonsRouteChildren: MaisonsRouteChildren = {
  MaisonsSlugRoute: MaisonsSlugRoute,
}

const MaisonsRouteWithChildren =
  MaisonsRoute._addFileChildren(MaisonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurateurRoute: ConfigurateurRoute,
  ContactRoute: ContactRoute,
  MaisonsRoute: MaisonsRouteWithChildren,
  RealisationsRoute: RealisationsRoute,
  SavoirFaireRoute: SavoirFaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
